### ISSUE TITLE
Filter option for trkpts above a specified speed 

### ISSUE THREAD

**Issue by moveson** [GPSBabel/gpsbabel#102]
GPX tracks in mountainous areas often include erroneous data resulting from signal bounce. These points are often obvious to humans viewing a track on a map, as they will deviate significantly from an otherwise expected path.

These data points will typically have an imputed speed (calculated as distance from the previous trkpt divided by time since the previous trkpt) that is unreasonably high. For example, the GPX track may be for a hiker, and the imputed speed at a given point may be 20 mph (32 kph) or even higher.

I would love to see a filter option that would remove points above a given imputed speed as provided by the user. The algorithm would need to remove points iteratively; that is to say, when one bad data point is removed, the calculations would need to be performed again to see if surrounding data points are bad.

**Comment by robertlipe** [comment]
If the GPS stores DOP info, you can usually toss the points with bad DOP (dilution of precision) via our discard filter https://www.gpsbabel.org/htmldoc-development/filter_discard.html

If your GPS is zinging you to another location, dropping a dozen points there, and then zinging you back when it regains fix, but doesn't TELL YOU that it had a bad signal, your best bet is probably the simplify filter and it may take a couple of passes of the data with a rather non-formulaic process. I'll often use one pass just to reduce the number of points and then another to reduce the amount of error in the track.  https://www.gpsbabel.org/htmldoc-development/filter_simplify.html

We're able to do this because MOST GPSes don't actually know speed; they know location and time and derive speed. 

Asking on the mailing list would have gained you a larger audience. This topic has been covered there many times before and probably should be incorporated into our FAQ. That's the probable work output in this bugreport...
