### ISSUE TITLE
End artificial start=, stop= whole second restriction

### ISSUE THREAD

**Issue by jidanni** [gpsbabel/gpsbabel#1024]
Here our track is sliced into nice half second segments,
but due to the "artificial" restriction of start= and stop= being whole
seconds, we encounter:
```
-x interpolate,time=0.5 -x track,start=20221221032537.5,stop=20221221032538.5
trackfilter-range-check: Invalid value for option "20221221032537.5"!
```

I mean imagine it's year 2222 and everybody is zipping around real fast.
Traffic tickets are being issued for microsecond violations and
gpsbabel is still thinking in seconds.

In real life I can [query the position of a plane at a particular second](https://www.jidanni.org/comm/air/routes/programs/gps/tips.html).
But my cellphone camera's Exif also have the microsecond,
and airplanes travel many meters per second,
so the only block on me being able to get a more precise answer
for where the plane was is this artificial restriction.

Anyway please allow
`-x interpolate,time=A.B -x track,start=C.D,stop=E.F`
where all six need not be related.
I.e., the two terminal points need not be on a node,
but should still have the correct position at that point.
Yes the user might get irregularly  spaced nodes
`o-o---o---o---o---o---o---oo `at the ends, but that is what he requested
via the start=, stop= parameters.

**Comment by robertlipe** [comment]
Please try the development snapshots. There's been some sub-second work in
the track filter since the last release. I don't think
https://github.com/GPSBabel/gpsbabel/pull/944/files is a direct hit, but it
certainly makes the situation better.

I'm on a phone RN, but I don't think that error even appears in the current
code....

**Comment by tsteven4** [comment]
The interpolate filter has supported subsecond interpolation since 1.7.0.  As I have explained in #1023 it does not guarantee an exact sample rate.

The track filter start and stop times are currently restricted to integral seconds.

At best we support millisecond resolutions, not microseconds.  This is the resolution supported by [QTime](https://doc.qt.io/qt-6/qtime.html), which we use to store all our time data.

The track filter does not generate points at the stop and start times.  the start/stop operation just selects a set of existing points.  if a point exists at the start(stop) time then it is included.

**Comment by tsteven4** [comment]
#1026 adds millisecond resolution for the track filter start and stop options.

**Comment by tsteven4** [comment]
@jidanni The change has been merged.  Can you build and try it?

**Comment by jidanni** [comment]
Erg... no worries, in a couple years it will get to Debian, and if I'm not in the Old Folks home and had my porridge...

Anyways, I'll trust you! Besides, what if I found another bug trying, that would only increase your work :->

Anyways, don't worry, I'm sure it works. You see I already labeled all my hobby pics, so it's on to the next adventure.
