### ISSUE TITLE
Push a 1.5.3?

### ISSUE THREAD

**Issue by cemeyer** [GPSBabel/gpsbabel#16]
It's been 11 months since 1.5.2 was released (January).  Maybe we should push a 1.5.3.

1.5.2 is tripping over .fit files from my Garmin ForeRunner 230 with "fit: Bad field size in data message".  I suspect https://github.com/gpsbabel/gpsbabel/commit/d6ec2fedf65c54151baa6b4bf26528be5fa715ca or https://github.com/gpsbabel/gpsbabel/commit/ff0dea7afa0f6a02461a7e4dabdc4cf43ca91a7b may resolve the problem.  Neither is present in 1.5.2.

**Comment by cemeyer** [comment]
(Yep, the file is successfully parsed with git master.)

**Comment by tsteven4** [comment]
that is probably the most common complaint about 1.5.2.

**Comment by robertlipe** [comment]
I hope/plan to push a 1.5.3 over the holidays, though I don't think I said
that out loud.  As I'm currently on the "wrong" continent, but returning
about twelve hours from now, but have pressing personal matters upon my
return, it'll probably be after Christmas and perhaps even closer to New
Years.

If any of you have pressing changes to be merged (I know the Garmin USB
encoding thing is still in flight - it's not contentious, I just haven't
done it...) please bang a gong soon(ish).

Given that this should be just a minor maintenance release, I'll bump the
minor number, push a new doc set, and won't bother with a beta because
respinning a beta to make it not a beta isn't actually any easier than
spinning another version.

Obrigada. (LANG=pt_BR)
RJL

**Comment by cemeyer** [comment]
Cool, works for me.

**Comment by alanbur** [comment]
After the move to GitHub where is the correct place to log bugs? According to the website it's the still developers mailing list. Either way I sent a mail about a bug with EXIF writing to the mailing list, it would be good if that could be fixed in 1.5.3 as it looks like it's just a 1-line typo in exif.cc - see http://sourceforge.net/p/gpsbabel/mailman/gpsbabel-code/thread/5687EE30.4040108%40gmail.com/#msg34734204

**Comment by cemeyer** [comment]
A new Github Issue or the mailing list, but certainly not on an unrelated issue (this one).

**Comment by alanbur** [comment]
I asked here because of the comment above asking if there were any pressing issues, and it not being clear where bugs now need to go. I've logged https://github.com/gpsbabel/gpsbabel/issues/19
