### ISSUE TITLE
Alignment issue on SPARC64 in saroute.cc reader

### ISSUE THREAD

**Issue by ra1fh** [GPSBabel/gpsbabel#29]
When running "make check" on OpenBSD/sparc64 5.8 configured to use the system compiler (gcc-4.2.1), I found this:

```
Running ./testo.d/saroute.test
Bus error (core dumped)
```

GDB shows this:

```
Program terminated with signal 10, Bus error.
#0  my_read () at saroute.cc:371
371             memcpy(&mylatlon,latlon,sizeof(mylatlon));
(gdb) list
366             double lon;
367     
368             wpt_tmp = new Waypoint;
369     
370             // copy to make sure we don't violate alignment restrictions.
371             memcpy(&mylatlon,latlon,sizeof(mylatlon));
372             lat = (0x80000000UL -
373                    le_read32(&mylatlon.lat)) /
374                   (double)(0x800000);
375             lon = (0x80000000UL -
```

That's interesting because the memcpy was apparently put in place to avoid such issues. Looking at disass, it seems the memcpy has been inlined using a 8 byte load instruction for the source pointer:

```
(gdb) info registers
...
i3             0x8dbd06b04a     608761720906
...
pc             0x8b1bb44440     0x8b1bb44440 <my_read+1792>
npc            0x8b1bb44444     0x8b1bb44444 <my_read+1796>

(gdb) disass
0x0000008b1bb4443c <my_read+1788>:      mov  %o0, %l1
0x0000008b1bb44440 <my_read+1792>:      ld  [ %i3 ], %g2              ; <------- SIGBUS
0x0000008b1bb44444 <my_read+1796>:      mov  %i4, %o0
```

As you can see the address in %i3 is not 8 byte aligned. So gcc should place a call to libc memcpy rather then inlining it with non-aligned load. Apparently gcc is free to do inlining here since pointers to structs still need to have correct alignment, otherwise the behaviour is undefined (at least that's what searching for issues like this suggests).

To fix this, adding a forced non-inlined memcpy and using that in line 371 helps:

``` C
#if defined(__GNUC__) && __GNUC__ > 3
__attribute__ ((__noinline__))
#endif
static void*
safe_memcpy(void *dst, const void *src, size_t len)
{
  return memcpy(dst, src, len);
}
```

Another option in this case is to use gcc-4.9 from OpenBSD ports, which doesn't inline memcpy in this location.

Since there is an easy workaround (using gcc-4.9) and the platorm/compiler/input format combination is probably not in widespread use anyway, I'd be fine with closing this bug as wontfix. I just wanted to document this in case there might be some other platforms and compilers affected by similar bugs.

**Comment by robertlipe** [comment]
Future readers of this thread that are interested in this will be served by
the terms 'type punning' and 'strict aliasing'.

GPSBabel, much like any code that implements protocol-ish things, tends to
abuse the rules a LOT when trying to up-convert a stream of bytes into
doubles or ints or 'real' data types.  Casting from a void\* to pretty much
anything other than a char tends to be a recipie for disaster - it's also
why malloc() and friends are forced to pad allocations to be suitably
aligned for the largest sensible data type - certainly a long double,
though some will even apply alignment for SIMD-type instructions.

We get away with a lot of this because x86 doesn't require strictly aligned
types.  If you want to read a word that's aligned on a half-word boundary,
the x86 based processors will let you. (There are some funkiness about bus
accesses and atomicity that don't apply here, but in my past life as an OS
guy and a firmware developer, I had to care...)  After Macs quit being
Power PC and Sparc lost its relevance in general purpose computing, x86 is
about the only thing GPSBabel runs on these days.  This also means a lot of
our endianness handling in newer formats hasn't been well vetted. While
there are lots of other CPUs around, the reality is that GPSBabel tends to
not get used on Sparc64 or MIPS or Itanium or such. We up and downcast
things pretty willy nilly.

I was a GCC maintainer when Mark Mitchell and others added type based alias
analysis and others in the project started really using the latitude
granted to them by the specification of the language. A lot of code broke
in that era because what programmers "knew" to be true was just plain
wrong. I spent enough time watching patient explanations of that era (and
completely unnecessary mudslinging) to really question code like that
above. I _think_ that since mylatlon starts with an int32_t, it has to be
32-bit aligned, but not 64 bit aligned, so I don't think a 64bit move is
safe. I wouldn't dig in my heels on that.  A later version of GCC acting
differently suggests there may have indeed been an issue that was fixed. It
could probably be helped by unioning la/lon with a int64 but again, I'd
have to think about it more.

So thank you for exercising that combination, but I think you're right -
this was probably just a GCC bug that's since been fixed. You're certainly
correct that the intersection of Sparc64|OpenBSD|saroute is incredibly tiny.
