### ISSUE TITLE
Proximity alerts imply parser failure on non speed "@" use

### ISSUE THREAD

**Issue by dexterbg** [GPSBabel/gpsbabel#49]
Conversion fails completely if adding proximity alerts on a KML to GPI conversion with "@" in placemark names not meant to be interpreted as speed alerts:

error.kml:
`<?xml version="1.0" encoding="utf-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>Test</name><Placemark><name>LAN@Work GmbH</name><Point><coordinates>10.3593499999999,48.98379</coordinates></Point></Placemark></Document></kml>`

> gpsbabel -i kml -f error.kml -o garmin_gpi,proximity=100m -F error.gpi
> garmin_gpi: Unsupported speed unit 'Work GmbH' in item 'Work GmbH'!

Maybe an invalid speed unit could simply be a warning instead of a fatal error? Another option would be to allow enabling proximity alerts without implying speed alert parsing.

**Comment by GPSBabelDeveloper** [comment]
If you enable proximity unit parsing for things after an @ and then use @ with non-numeric values and without units, you're probably going to have a bad time. Still, I made these into a warning instead of an error in 4532ceb. I'm not totally sure if that'll parse as "0 km/h" but at least it's no longer fatal. Please check out the latest sources and experiment.
