### ISSUE TITLE
Cleanup source tree

### ISSUE THREAD

**Issue by SunBlack** [GPSBabel/gpsbabel#665]
I came across this project because it supports a format that we had previously included otherwise and I saw that GDAL can handle it via this project here.  The disadvantage of this project is that you can't include it as a dynamic or static library. Good one: CMake is already used, nevertheless it looks like a pain to add here sth., as the repo contains a lot of stuff which isn't really necessary:

* As CMake is supported, there is no need for further IDE projects (MSVC, XCode, qmake, ...), as CMake can generate this solutions
* 3rd-Party code (like shapelib) can be easily included via CMake

If you want I can help you to cleanup the project und use CMake how it is intended.

**Comment by tsteven4** [comment]
Welcome.  Sorry for the delay, we were migrating to a new continuous integration system.

The current state of our build support is described in the [INSTALL file](https://github.com/GPSBabel/gpsbabel/blob/master/INSTALL).

We recently retired our autotools (configure) based build system, and made qmake our reference build system.  The cmake support is experimental and incomplete.  It was originally added just to load the project into JetBrains CLion.

In order of difficulty the build system needs to

1. support building on the machine at hand
2. support building on all our operating systems and their supported toolchains.
3. support the needs of packagers.

The needs of the packagers are particularly difficult to meet and validate.  We don't know the complete set of packagers, understand their packaging systems and constraints, have access to their systems, or have a way to validate support for their needs.  For those that we do know communication can be sporadic.  Despite that we have vetted our qmake reference system with as many packagers as we could contact.

We anticipate eventually making cmake our reference build system and dropping support for qmake, but we are not ready to do so at this time.  However, we are open to improving our cmake implementation to the extent it can be done while maintaining the existing qmake support.  We realize cmake can generate qmake .pro files but in our experience translations of this type often are not fully functional.

Given that we want to maintain the qmake support, it is desirable to have the CMakeLists.txt file parallel those of the qmake .pro files when possible for ease maintenance and comparison.

We have considered a hierarchical build.  We are reluctant to rearrange the project directory structure as it makes examining history, especially on GitHub, more difficult.  Eventually we will go to a hierarchical build and likely rearrange the directory structure, but again at this point we want to maintain full functionality of the qmake build system.

We are unlikely to want to create an API to a gpsbabel library.  We any interface other than the current command line interface would be unstable and be a burden to maintain.  What we do in our graphical user interface, and what Google Earth does, is start a gpsbabel process and pass commands via the existing command line interface.

We apologize for any confusion caused by some of the debris in the project.  Some of that needs to get cleaned up.

We realize the maintenance of parallel build systems is both a burdensome and constraining.  However, if while doing so you can offer suggestions or PRs to improve our cmake support or make it more complete we would be happy to consider them.
