### ISSUE TITLE
xmapwpt.xml document lost

### ISSUE THREAD

**Issue by tsteven4** [gpsbabel/gpsbabel#754]
It was deleted here https://github.com/GPSBabel/gpsbabel/commit/25473724b087ccdc077289eba79904a9c9ed7545 in an apparently unrelated changeset, but the format is still active.  It is a style file, so it is low maintenance.

Do we want to delete the style or restore the lost document?

**Comment by robertlipe** [comment]
I could go either way, but this was pretty clearly a screwup of mine. Sorry.

PocketPC is clearly long dead - and was barely alive when it wasn't - but this wasn't a conscious decision to kill it. Maybe we should escalate that decision since I apparently wounded it.

If agreed, do you want to drop the .style file or shall I?

**Comment by tsteven4** [comment]
I'll kill it.

**Comment by tsteven4** [comment]
Shall we kill xmap and xmap2006 as well?

**Comment by robertlipe** [comment]
Yes, please. Delorme mapping products are long dead.

**Comment by tsteven4** [comment]
closed via #757
