### ISSUE TITLE
unmatched tags in geocache reference file

### ISSUE THREAD

**Issue by tsteven4** [gpsbabel/gpsbabel#895]
1. https://github.com/GPSBabel/gpsbabel/blob/8dae11e100677217c6b4cd858a76f3bf6bc8d12c/reference/gc/GCGCA8.gpx#L46
The tags &lt;/a&gt;&lt;/p&gt; are unmatched.
This causes the output from gpsbabel -i gpx -f reference/gc/GCGCA8.gpx -o html -F GCGCA8.html to contain unmatched tags.
2. There is an additional problem.  The P end tag we add after gpsbabeldesclong is unmatched because of the UL tags in what we think is the paragraph content.

**Comment by robertlipe** [comment]
That HTML was created by hand (mine) that was rendered inside an iframe of
browsers and using crudest tools almost 20 years ago. It's even possible
that it wasn't even really written in 'real' HTML as I think the cache page
editor of that time used sort of a bbcode markup that was transcribed on
the server.

As long as we can approximately round-trip what's inside
groundspeak:long_description,
what we do with that HTML is up to us. That cache placement has long since
been removed and out of circulation. There's no need to overthink keeping
it in sync with a master copy or whatever.

We're free to change that reference file and the ones that come from it as
we see fit. We're free to edit the past if it makes the present or future
better.

Signed,
Winston Smith

**Comment by robertlipe** [comment]
Is there remaining action here? That embedded HTML snippet is from ancient browser days, when <p>s were considered self closing. (This was before even XHTML.) It's certainly in "quirks mode" even if it's not outright broken.

If you're OK with me deleting &lt;/a&gt;&lt;/p&gt at the end of long description and fixing any fallout reference files I'll do that. It's trying to close a link that's not here  and a paragraph that was never opened. That's just copy-paste error in the source material from the Mozilla 1.5 era or so...

We're not testing the validity of our embedded HTML, so I don't think we have to faithfully reproduce/handle/fix what was clearly broken HTML. 

I'm happy to do the fix if you agree that's OK.

**Comment by robertlipe** [comment]
Sticking a note to https://github.com/GPSBabel/gpsbabel/pull/1196

**Comment by tsteven4** [comment]
> 2\. There is an additional problem.  The P end tag we add after gpsbabeldesclong is unmatched because of the UL tags in what we think is the paragraph content.

Point 2. was fixed in dcdbb6a90353231497273d3062c2cd5d396e1d6e

**Comment by tsteven4** [comment]
> 1. The tags ```</a></p>``` are unmatched.

Point 1. is fixed in #1196, and updated version of GCGCA8.gpx.
